### ISSUE TITLE
Demo EVENT messages in `cloudiot_mqtt_example.py` are not being sent once every second.

### ISSUE THREAD

**Issue by ahrarmonsur** [googleapis/python-iot#189]
#### Overview
The comment in the following code block says that that EVENT messages should be sent every second, but STATE messages should be sent with a longer cadence. However, the logic waits the longer period (60 seconds) for all message types.

#### Code block

https://github.com/googleapis/python-iot/blob/main/samples/api-client/mqtt_example/cloudiot_mqtt_example.py#L475-L478
Currently
```python
        # Send events every second. State should not be updated as often
        for i in range(0, 60):
            time.sleep(1)
            client.loop()
```

Suggestion
```python
        # Send events every second. State should not be updated as often
        WAIT_IN_SECONDS = 1 if args.message_type == 'event' else 60
        for i in range(0, WAIT_IN_SECONDS):
            time.sleep(1)
            client.loop()
```

#### Environment details

  - OS type and version: Raspbian GNU/Linux 10 (buster)
  - Python version: 3.7.3
  - pip version: 21.2.4
  - `google-cloud-iot` version: 2.2.1

**Comment by parthea** [comment]
Hi @codepriestz,
Please could you take a look?
