### ISSUE TITLE
400 The field 'parent' must be in the form 'projects/{project}/locations/{location}'.

### ISSUE THREAD

**Issue by Korzhak** [googleapis/python-iot#25]
I tried a sample code from the documentation and got this error: `google.api_core.exceptions.InvalidArgument: 400 The field 'parent' must be in the form 'projects/{project}/locations/{location}'.`

**My code (from example https://googleapis.dev/python/iot/latest/index.html):** 
```python
from google.cloud import iot_v1
import os

os.environ['GOOGLE_APPLICATION_CREDENTIALS'] = 'iot-core-test.json'


client = iot_v1.DeviceManagerClient()

parent = client.registry_path('iot-core-test-<id>', 'europe-west1', 'iot-sample-registry')

for page in client.list_device_registries(parent).pages:
    for element in page:
        # process element
        pass
```

**Debug error string:**
```json
debug_error_string = "{"created":"@1596288752.579561214","description":"Error received from peer ipv4:216.58.215.74:443","file":"src/core/lib/surface/call.cc","file_line":1055,"grpc_message":"The field 'parent' must be in the form 'projects/{project}/locations/{location}'.","grpc_status":3}"
```

**About:**
- Python 3.8.2
- google-cloud-iot==1.0.0
- Ubuntu 20.04.1 LTS

**Comment by munkhuushmgl** [comment]
Looks like you do not need 'iot-sample-registry' as parameter if you are trying to list device registries.
Here is the correct example of how to list device registries:

https://github.com/GoogleCloudPlatform/python-docs-samples/blob/a8800ff8c6c88618dbe52a2ff2e4beecc788de85/iot/api-client/manager/manager.py#L346

this should solve your problem.

**Comment by munkhuushmgl** [comment]
With the note above, I am closing this issue.

Feel free to reopen if you are still having issue with this.
