### ISSUE TITLE
Cloud IoT Core Python mqtt example waits 60 seconds between messages, inconsistent with the Readme

### ISSUE THREAD

**Issue by zacharesmer** [googleapis/python-iot#356]
#### Environment details

  - OS type and version: Ubuntu 20.10
  - Python version: 3.10
  - pip version: 22.1.2
  - `google-cloud-iot` version: 2.5.1

#### Steps to reproduce

  1. Follow steps in the Readme, create and register a device in IoT Core, set up authentication
 2. Run `python cloudiot_mqtt_example.py --algorithm="RS256" --cloud_region="us-central1" --device_id="my-device" --private_key_file rsa_private.pem --project_id="my-project-id" --registry_id="my-registry" device_demo
python cloudiot_mqtt_example.py --algorithm="RS256" --cloud_region="us-central1" --device_id="hexagon0" --private_key_file rsa_private.pem --project_id="imposing-medium-358202" --registry_id="hexagon-registry" device_demo` (but with the actual project, device, and registry names)
3. The messages publish correctly, but 60 seconds apart instead of one second apart as described in the readme and a comment.

#### Code example
It looks like this is caused by the nested for loop starting in line 566 of [cloudiot_mqtt_example.py](https://github.com/googleapis/python-iot/blob/HEAD/samples/api-client/mqtt_example/cloudiot_mqtt_example.py#L566) . I tried running it with that loop removed and `time.sleep(1)` in the main loop, and it works as described (approximately one message per second).

Or, if once every 60 seconds is the expected behavior, then the readme and comment in line 565 are wrong.

#### Stack trace
N/A

**Comment by parthea** [comment]
Closing as obsolete as the service is being retired on August 16, 2023.

```
Google Cloud IoT Core is being retired on August 16, 2023. Contact your Google Cloud account team for more information.
```
https://cloud.google.com/iot-core
https://cloud.google.com/iot/docs
