### ISSUE TITLE
"Device" can't be pickled

### ISSUE THREAD

**Issue by samurang87** [googleapis/python-iot#42]
Hello!

It looks like the "Device" class can't be pickled anymore with your latest major release. We'd like to upgrade to v.2+ but our tests that use multiprocessing fail because of this reason.

#### Environment details

  - OS type and version: local Mac OS 10.15.7, docker python-base:3.8.3-slim-buster
  - Python version: 3.8.3
  - pip version: 20.1.1
  - `google-cloud-iot` version: 2.0.1

#### Steps to reproduce

Try to pickle

#### Code example and resulting stack trace

```python
import pickle
from google.cloud.iot_v1 import Device

device = Device(id="1")
pickled_device = pickle.dumps(device)
print(pickled_device)
```
Result:
```
Traceback (most recent call last):
  File "/Users/cmezzavilla/Code/aratrum/.vscode/scratch.py", line 7, in <module>
    pickled_device = pickle.dumps(device)
_pickle.PicklingError: Can't pickle <class 'Device'>: it's not the same object as __main__.Device
```

#### Stack trace from test

We have some tests running with multiprocessing, and when trying to upgrade python-iot from 1.0.0 to 2.0.1 they fail like so:

```
cls = <class 'multiprocessing.reduction.ForkingPickler'>
obj = ('108ed2f80', '__setitem__', ('europe-west1', {'pytest-of-cmezzavilla_aratrum_pytest-1': {'dev_26': id: "dev_26"
name:...pytest-of-cmezzavilla_aratrum_pytest-1/devices/dev_26"
config {
  version: 1
  binary_data: "invalid config"
}
}}), {})
protocol = None

    @classmethod
    def dumps(cls, obj, protocol=None):
        buf = io.BytesIO()
>       cls(buf, protocol).dump(obj)
E       _pickle.PicklingError: Can't pickle <class 'Device'>: attribute lookup Device on __main__ failed
```

**Comment by munkhuushmgl** [comment]
@busunkim96 I barely know anything about pickle, Could you answer this question if you have some context?

Otherwise, I will try to find someone else.

**Comment by busunkim96** [comment]
Hi,

If you need to serialize an object use we recommend using one of the serialization methods provided by `proto.Message`.

https://proto-plus-python.readthedocs.io/en/latest/messages.html#serialization

```py
from google.cloud.iot_v1 import Device

device = Device(id="1")

# Bytes
serialized_device = Device.serialize(device)
device_from_bytes = Device.deserialize(serialized_device)

# JSON String
json_device = Device.to_json(device)
device_from_json = Device.from_json(json_device)

assert device == device_from_bytes
assert device == device_from_json
```

**Comment by samurang87** [comment]
> Hi,
> 
> If you need to serialize an object use we recommend using one of the serialization methods provided by `proto.Message`.
> 
> https://proto-plus-python.readthedocs.io/en/latest/messages.html#serialization


This is good to know, thanks!

Do you know a way to deal with pickling happening outside our control, like with multiprocessing?

**Comment by busunkim96** [comment]
From a discussion with @tswast, you should pass the serialized device `Device.serialize(device)` instead of the plain `Device` to the multiprocessing method you are using.

I've opened https://github.com/googleapis/proto-plus-python/issues/162 to see if pickling is something we want to support. Note that the protobuf serialization is better able to handle schema changes.

https://developers.google.com/protocol-buffers/docs/pythontutorial#why-use-protocol-buffers

**Comment by tswast** [comment]
> Do you know a way to deal with pickling happening outside our control, like with multiprocessing?

With multiprocessing, there are two ways of passing data around.

1. When the process "forks" you can access global variables. This actually works by copy-on-write of the process memory, so no pickling in this case.

2. Passing data as arguments to and return from functions such as `multiprocessing.map`. In these cases, you should pass around `bytes` using the `serialize` functions as @busunkim96 mentioned.

**Comment by samurang87** [comment]
@tswast @busunkim96 Thanks a lot for the support!
