### ISSUE TITLE
Can't get actual last heartbeat and event time from iot device using python SDK

### ISSUE THREAD

**Issue by gBeridze94** [googleapis/python-iot#46]
Hello. I am trying to to get last heartbeat and event time from IOT Device using python sdk.  A while ago I noticed that my code stopped working 
`    for device in device_client.list_devices(parent):
        last_event = device.last_event_time.seconds
        last_heartbeat = device.last_heartbeat_time.seconds`
. I also tried to migrate code to 2.0, but with same results. Value is always 0. 
[https://cloud.google.com/iot/docs/reference/cloudiot/rest/v1/projects.locations.registries.devices/get#http-request](url) request and gcp console itself, contains correct value for this fields. 
Is there an issue with sdk itself?
Thanks in advance

**Comment by munkhuushmgl** [comment]
I think its SDK issue.

**Comment by gcseh** [comment]
Try to include the corresponding fieldMask in the request:
```python
mask = gp_field_mask.FieldMask()
mask.paths.append("last_heartbeat_time")

devices = list(client.list_devices(request={"parent": registry_path, "field_mask": mask}))
```
Please re-open this issue if still exists.
