### ISSUE TITLE
Erroneous google-cloud-iot version in "manager" sample

### ISSUE THREAD

**Issue by pikulm** [googleapis/python-iot#52]
The following:
https://github.com/googleapis/python-iot/blob/93c47da76a05e5e3f891556f1d3416ce18db9580/samples/api-client/manager/requirements.txt#L6
should be changed to version 2.0.1.

Current version leads to an error in this function:
https://github.com/googleapis/python-iot/blob/93c47da76a05e5e3f891556f1d3416ce18db9580/samples/api-client/manager/manager.py#L554-L556

**Comment by munkhuushmgl** [comment]
Thanks for opening this issue, I will start the work for this.
